"""add price column

Revision ID: 3179abb32551
Revises: 3a79b59eb9de
Create Date: 2023-06-25 12:54:29.489554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3179abb32551'
down_revision = '3a79b59eb9de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gunplas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gunplas', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
