"""added skill column

Revision ID: 677cbd052ae8
Revises: 82774bea5b4c
Create Date: 2023-06-29 11:32:23.509537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '677cbd052ae8'
down_revision = '82774bea5b4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skill_level', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('skill_level')

    # ### end Alembic commands ###
