"""empty message

Revision ID: 77e048aa2910
Revises: 677cbd052ae8
Create Date: 2023-06-29 12:26:40.803315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77e048aa2910'
down_revision = '677cbd052ae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('gunpla_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gunpla_id'], ['gunplas.id'], name=op.f('fk_comments_gunpla_id_gunplas')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_comments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # ### end Alembic commands ###
