"""add image column to gunpla

Revision ID: cd0ca9dbb8a5
Revises: 3179abb32551
Create Date: 2023-06-25 14:44:27.643068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd0ca9dbb8a5'
down_revision = '3179abb32551'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gunplas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_img', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gunplas', schema=None) as batch_op:
        batch_op.drop_column('model_img')

    # ### end Alembic commands ###
